###**Task C1**

#Ndiye Stimela 02/10/2026
###Weather pattern exploration given weather data.
 file im given i must explore weather patterns and inspect, clean, summarize and visualize the data working as a junior data analyst

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/weather_data.csv")
df.head()

,Temperature,Humidity,Wind Speed,Precipitation (%),Cloud Cover,Atmospheric Pressure,UV Index,Season,Visibility (km),Location,Weather Type
0,14.0,73,9.5,82.0,partly cloudy,1010.82,2,Winter,3.5,inland,Rainy
1,39.0,96,8.5,71.0,partly cloudy,1011.43,7,Spring,10.0,inland,Cloudy
2,30.0,64,7.0,16.0,clear,1018.72,5,Spring,5.5,mountain,Sunny
3,38.0,83,1.5,82.0,clear,1026.25,7,Spring,1.0,coastal,Sunny
4,27.0,74,17.0,66.0,overcast,990.67,1,Winter,2.5,mountain,Rainy

###Task C2

In [4]:
df.head(10)

,Temperature,Humidity,Wind Speed,Precipitation (%),Cloud Cover,Atmospheric Pressure,UV Index,Season,Visibility (km),Location,Weather Type
0,14.0,73,9.5,82.0,partly cloudy,1010.82,2,Winter,3.5,inland,Rainy
1,39.0,96,8.5,71.0,partly cloudy,1011.43,7,Spring,10.0,inland,Cloudy
2,30.0,64,7.0,16.0,clear,1018.72,5,Spring,5.5,mountain,Sunny
3,38.0,83,1.5,82.0,clear,1026.25,7,Spring,1.0,coastal,Sunny
4,27.0,74,17.0,66.0,overcast,990.67,1,Winter,2.5,mountain,Rainy
5,32.0,55,3.5,26.0,overcast,1010.03,2,Summer,5.0,inland,Cloudy
6,-2.0,97,8.0,86.0,overcast,990.87,1,Winter,4.0,inland,Snowy
7,3.0,85,6.0,96.0,partly cloudy,984.46,1,Winter,3.5,inland,Snowy
8,3.0,83,6.0,66.0,overcast,999.44,0,Winter,1.0,mountain,Snowy
9,28.0,74,8.5,107.0,clear,1012.13,8,Winter,7.5,coastal,Sunny

In [5]:
df.tail(10)

,Temperature,Humidity,Wind Speed,Precipitation (%),Cloud Cover,Atmospheric Pressure,UV Index,Season,Visibility (km),Location,Weather Type
13190,30.0,24,3.5,16.0,partly cloudy,1017.54,11,Summer,6.5,mountain,Sunny
13191,27.0,48,6.5,14.0,clear,1029.37,8,Summer,8.0,inland,Sunny
13192,31.0,24,8.0,5.0,clear,1029.61,8,Summer,9.0,inland,Sunny
13193,-5.0,65,15.5,50.0,overcast,982.57,1,Winter,5.0,inland,Snowy
13194,29.0,62,13.0,17.0,overcast,1002.81,2,Spring,5.0,coastal,Cloudy
13195,10.0,74,14.5,71.0,overcast,1003.15,1,Summer,1.0,mountain,Rainy
13196,-1.0,76,3.5,23.0,cloudy,1067.23,1,Winter,6.0,coastal,Snowy
13197,30.0,77,5.5,28.0,overcast,1012.69,3,Autumn,9.0,coastal,Cloudy
13198,3.0,76,10.0,94.0,overcast,984.27,0,Winter,2.0,inland,Snowy
13199,-5.0,38,0.0,92.0,overcast,1015.37,5,Autumn,10.0,mountain,Rainy

In [12]:
df.shape

(13200, 11)

In [13]:
df.columns

Index(['Temperature', 'Humidity', 'Wind Speed', 'Precipitation (%)',
       'Cloud Cover', 'Atmospheric Pressure', 'UV Index', 'Season',
       'Visibility (km)', 'Location', 'Weather Type'],
      dtype='object')

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13200 entries, 0 to 13199
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Temperature           13200 non-null  float64
 1   Humidity              13200 non-null  int64
 2   Wind Speed            13200 non-null  float64
 3   Precipitation (%)     13200 non-null  float64
 4   Cloud Cover           13200 non-null  object
 5   Atmospheric Pressure  13200 non-null  float64
 6   UV Index              13200 non-null  int64
 7   Season                13200 non-null  object
 8   Visibility (km)       13200 non-null  float64
 9   Location              13200 non-null  object
 10  Weather Type          13200 non-null  object
dtypes: float64(5), int64(2), object(4)
memory usage: 1.1+ MB

In [15]:
df.describe()

,Temperature,Humidity,Wind Speed,Precipitation (%),Atmospheric Pressure,UV Index,Visibility (km)
count,13200.000000,13200.000000,13200.000000,13200.000000,13200.000000,13200.000000,13200.000000
mean,19.127576,68.710833,9.832197,53.644394,1005.827896,4.005758,5.462917
std,17.386327,20.194248,6.908704,31.946541,37.199589,3.856600,3.371499
min,-25.000000,20.000000,0.000000,0.000000,800.120000,0.000000,0.000000
25%,4.000000,57.000000,5.000000,19.000000,994.800000,1.000000,3.000000
50%,21.000000,70.000000,9.000000,58.000000,1007.650000,3.000000,5.000000
75%,31.000000,84.000000,13.500000,82.000000,1016.772500,7.000000,7.500000
max,109.000000,109.000000,48.500000,109.000000,1199.210000,14.000000,20.000000

In [16]:
df.isnull().sum()

Temperature             0
Humidity                0
Wind Speed              0
Precipitation (%)       0
Cloud Cover             0
Atmospheric Pressure    0
UV Index                0
Season                  0
Visibility (km)         0
Location                0
Weather Type            0
dtype: int64

In [17]:
df.duplicated().sum()

np.int64(0)

###Explanations of code
df.shape = it checks the rows and columns of the dataset that was given. the dataset contains  13200 rows , 11 columns.

df.columns = shows all columns displayed on the dataset. the columns contained are:
'Temperature', 'Humidity', 'Wind Speed', 'Precipitation (%)',
       'Cloud Cover', 'Atmospheric Pressure', 'UV Index', 'Season',
       'Visibility (km)', 'Location', 'Weather Type'


df.info = it shows the datatypes of the columns used in the data. it shows we have 5 columns of datatype float, 2 columns of datatype integer and 4 columns of data type object


df.describe = generates a descriptive statistical summary of the data in the DataFrame using count, mean, standard deviation and minimum, maximum values


df.null().sum() = shows the missing values for the datafram, this dataframe has 0 data missing so all values are there and non is left out

df.duplicated().sum() = this one checks for duplicate values in the data set. it show that there are no duplicates. so if there is no missing values or duplicate values it increases the accuracy of predicting a more correct weather pattern or weather analysis of the data being given

###Task C3
from the analysis done:

*  there are no columns with missing values
*  there are no duplicated rows


*   In short the data was already clean and the data can be used for further   model prediction

###Task C4

In [34]:
df['temperature_category'] = np.resize(['cold', 'mild', 'warm', 'hot'], len(df))
#temperature_category can be useful if you want to know in general how it feels without knowing statistical data
df['wind_category'] = np.resize(['calm', 'breezy', 'windy', 'strong winds'], len(df))
#wind_category can be useful if you want to know in general how it feels without knowing statistical data
df['visibility_category'] = np.resize(['poor', 'moderate', 'Good'],len(df))
#visibility_category can be useful if you want to know in general how it feels without knowing statistical data
df['humidity_category'] = np.resize(['low', 'moderate', 'high'], len(df))
#humidity_category can be useful if you want to know in general how it feels without knowing statistical data
df

,Temperature,Humidity,Wind Speed,Precipitation (%),Cloud Cover,Atmospheric Pressure,UV Index,Season,Visibility (km),Location,Weather Type,temperature_category,wind_category,visibility_category,humidity_category
0,14.0,73,9.5,82.0,partly cloudy,1010.82,2,Winter,3.5,inland,Rainy,cold,calm,poor,low
1,39.0,96,8.5,71.0,partly cloudy,1011.43,7,Spring,10.0,inland,Cloudy,mild,breezy,moderate,moderate
2,30.0,64,7.0,16.0,clear,1018.72,5,Spring,5.5,mountain,Sunny,warm,windy,Good,high
3,38.0,83,1.5,82.0,clear,1026.25,7,Spring,1.0,coastal,Sunny,hot,strong winds,poor,low
4,27.0,74,17.0,66.0,overcast,990.67,1,Winter,2.5,mountain,Rainy,cold,calm,moderate,moderate
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13195,10.0,74,14.5,71.0,overcast,1003.15,1,Summer,1.0,mountain,Rainy,hot,strong winds,moderate,moderate
13196,-1.0,76,3.5,23.0,cloudy,1067.23,1,Winter,6.0,coastal,Snowy,cold,calm,Good,high
13197,30.0,77,5.5,28.0,overcast,1012.69,3,Autumn,9.0,coastal,Cloudy,mild,breezy,poor,low
13198,3.0,76,10.0,94.0,overcast,984.27,0,Winter,2.0,inland,Snowy,warm,windy,moderate,moderate
13199,-5.0,38,0.0,92.0,overcast,1015.37,5,Autumn,10.0,mountain,Rainy,hot,strong winds,Good,high

###Task C5

TypeError: agg function failed [how->mean,dtype->object]

In [41]:
df = plt.figure()
plt.show()

###Task c7

from the work i see that the data had


1.   no missing values
2.   no duplicate values
3.  good data structure
4. extremes are not far away from the median

the data needs more Input for more precise and accurate predictions. i believe that it was not sufficient data


my limitations is that it was  hard to use the groupby methods

i need to revise feature engineering more often